countries = [
    ["AE", "United Arab Emirates"],
    ["AF", "Afghanistan"],
    ["AL", "Albania"],
    ["AM", "Armenia"],
    ["AR", "Argentina"],
    ["AS", "American Samoa"],
    ["AT", "Austria"],
    ["AU", "Australia"],
    ["AZ", "Azerbaijan"],
    ["BA", "Bosnia and Herzegovina"],
    ["BB", "Barbados"],
    ["BD", "Bangladesh"],
    ["BE", "Belgium"],
    ["BG", "Bulgaria"],
    ["BH", "Bahrain"],
    ["BM", "Bermuda"],
    ["BN", "Brunei Darussalam"],
    ["BR", "Brazil"],
    ["BS", "Bahamas"],
    ["BT", "Bhutan"],
    ["BW", "Botswana"],
    ["BY", "Belarus"],
    ["BZ", "Belize"],
    ["CA", "Canada"],
    ["CG", "Congo"],
    ["CH", "Switzerland"],
    ["CL", "Chile"],
    ["CM", "Cameroon"],
    ["CN", "China"],
    ["CO", "Colombia"],
    ["CR", "Costa Rica"],
    ["CU", "Cuba"],
    ["CY", "Cyprus"],
    ["CZ", "Czechia"],
    ["DE", "Germany"],
    ["DJ", "Djibouti"],
    ["DK", "Denmark"],
    ["DM", "Dominica"],
    ["DO", "Dominican Republic"],
    ["DZ", "Algeria"],
    ["EC", "Ecuador"],
    ["EE", "Estonia"],
    ["EG", "Egypt"],
    ["ES", "Spain"],
    ["ET", "Ethiopia"],
    ["FI", "Finland"],
    ["FJ", "Fiji"],
    ["FK", "Falkland Islands (Malvinas)"],
    ["FO", "Faroe Islands"],
    ["FR", "France"],
    ["GA", "Gabon"],
    ["GB", "United Kingdom of Great Britain and Northern Ireland"],
    ["GD", "Grenada"],
    ["GE", "Georgia"],
    ["GF", "French Guiana"],
    ["GH", "Ghana"],
    ["GL", "Greenland"],
    ["GM", "Gambia"],
    ["GN", "Guinea"],
    ["GQ", "Equatorial Guinea"],
    ["GR", "Greece"],
    ["GT", "Guatemala"],
    ["GU", "Guam"],
    ["GW", "Guinea-Bissau"],
    ["GY", "Guyana"],
    ["HK", "Hong Kong"],
    ["HN", "Honduras"],
    ["HR", "Croatia"],
    ["HT", "Haiti"],
    ["HU", "Hungary"],
    ["ID", "Indonesia"],
    ["IE", "Ireland"],
    ["IL", "Israel"],
    ["IN", "India"],
    ["IQ", "Iraq"],
    ["IS", "Iceland"],
    ["IT", "Italy"],
    ["JE", "Jersey"],
    ["JM", "Jamaica"],
    ["JO", "Jordan"],
    ["JP", "Japan"],
    ["KE", "Kenya"],
    ["KH", "Cambodia"],
    ["KI", "Kiribati"],
    ["KM", "Comoros"],
    ["KR", "South Korea"],
    ["KW", "Kuwait"],
    ["KY", "Cayman Islands"],
    ["KZ", "Kazakhstan"],
    ["LB", "Lebanon"],
    ["LI", "Liechtenstein"],
    ["LK", "Sri Lanka"],
    ["LR", "Liberia"],
    ["LS", "Lesotho"],
    ["LT", "Lithuania"],
    ["LU", "Luxembourg"],
    ["LV", "Latvia"],
    ["LY", "Libya"],
    ["MA", "Morocco"],
    ["MC", "Monaco"],
    ["MG", "Madagascar"],
    ["MH", "Marshall Islands"],
    ["ML", "Mali"],
    ["MM", "Myanmar"],
    ["MN", "Mongolia"],
    ["MO", "Macao"],
    ["MV", "Maldives"],
    ["MX", "Mexico"],
    ["MY", "Malaysia"],
    ["MZ", "Mozambique"],
    ["NA", "Namibia"],
    ["NE", "Niger"],
    ["NG", "Nigeria"],
    ["NI", "Nicaragua"],
    ["NL", "Netherlands"],
    ["NO", "Norway"],
    ["NP", "Nepal"],
    ["NZ", "New Zealand"],
    ["PA", "Panama"],
    ["PE", "Peru"],
    ["PF", "French Polynesia"],
    ["PG", "Papua New Guinea"],
    ["PH", "Philippines"],
    ["PK", "Pakistan"],
    ["PL", "Poland"],
    ["PR", "Puerto Rico"],
    ["PT", "Portugal"],
    ["PY", "Paraguay"],
    ["QA", "Qatar"],
    ["RO", "Romania"],
    ["RS", "Serbia"],
    ["RU", "Russia"],
    ["RW", "Rwanda"],
    ["SA", "Saudi Arabia"],
    ["SB", "Solomon Islands"],
    ["SC", "Seychelles"],
    ["SD", "Sudan"],
    ["SE", "Sweden"],
    ["SG", "Singapore"],
    ["SI", "Slovenia"],
    ["SK", "Slovakia"],
    ["SL", "Sierra Leone"],
    ["SN", "Senegal"],
    ["SO", "Somalia"],
    ["SV", "El Salvador"],
    ["TD", "Chad"],
    ["TH", "Thailand"],
    ["TN", "Tunisia"],
    ["TR", "Turkey"],
    ["TT", "Trinidad and Tobago"],
    ["TW", "Taiwan"],
    ["TZ", "Tanzania"],
    ["UA", "Ukraine"],
    ["UG", "Uganda"],
    ["US", "United States of America"],
    ["UY", "Uruguay"],
    ["VE", "Venezuela"],
    ["VN", "Viet Nam"],
    ["WS", "Samoa"],
    ["ZA", "South Africa"],
    ["ZW", "Zimbabwe"]
]

realtime_countries = [
    ["AR", "Argentina"],
    ["AT", "Austria"],
    ["AU", "Australia"],
    ["BE", "Belgium"],
    ["BR", "Brazil"],
    ["CA", "Canada"],
    ["CL", "Chile"],
    ["CO", "Colombia"],
    ["CZ", "Czechia"],
    ["DE", "Germany"],
    ["DK", "Denmark"],
    ["EG", "Egypt"],
    ["ES", "Spain"],
    ["FI", "Finland"],
    ["FR", "France"],
    ["GR", "Greece"],
    ["HK", "Hong Kong"],
    ["IN", "India"],
    ["IT", "Italy"],
    ["JP", "Japan"],
    ["KE", "Kenya"],
    ["KR", "South Korea"],
    ["MX", "Mexico"],
    ["MY", "Malaysia"],
    ["NG", "Nigeria"],
    ["NL", "Netherlands"],
    ["NO", "Norway"],
    ["NZ", "New Zealand"],
    ["PH", "Philippines"],
    ["PL", "Poland"],
    ["PT", "Portugal"],
    ["RO", "Romania"],
    ["RU", "Russia"],
    ["SA", "Saudi Arabia"],
    ["SE", "Sweden"],
    ["TW", "Taiwan"],
    ["UA", "Ukraine"],
    ["US", "United States of America"],
]

states = [
    ["US-AL", "Alabama"],
    ["US-AK", "Alaska"],
    ["US-AZ", "Arizona"],
    ["US-AR", "Arkansas"],
    ["US-CA", "California"],
    ["US-CO", "Colorado"],
    ["US-CT", "Connecticut"],
    ["US-DE", "Delaware"],
    ["US-FL", "Florida"],
    ["US-GA", "Georgia"],
    ["US-HI", "Hawaii"],
    ["US-ID", "Idaho"],
    ["US-IL", "Illinois"],
    ["US-IA", "Iowa"],
    ["US-KS", "Kansas"],
    ["US-KY", "Kentucky"],
    ["US-LA", "Louisiana"],
    ["US-ME", "Maine"],
    ["US-MD", "Maryland"],
    ["US-MA", "Massachusetts"],
    ["US-MI", "Michigan"],
    ["US-MN", "Minnesota"],
    ["US-MS", "Mississippi"],
    ["US-MO", "Missouri"],
    ["US-MT", "Montana"],
    ["US-NE", "Nebraska"],
    ["US-NV", "Nevada"],
    ["US-NH", "New Hampshire"],
    ["US-NJ", "New Jersey"],
    ["US-NM", "New Mexico"],
    ["US-NY", "New York"],
    ["US-NC", "North Carolina"],
    ["US-ND", "North Dakota"],
    ["US-OH", "Ohio"],
    ["US-OK", "Oklahoma"],
    ["US-OR", "Oregon"],
    ["US-PA", "Pennsylvania"],
    ["US-RI", "Rhode Island"],
    ["US-SC", "South Carolina"],
    ["US-SD", "South Dakota"],
    ["US-TN", "Tennessee"],
    ["US-TX", "Texas"],
    ["US-UT", "Utah"],
    ["US-VT", "Vermont"],
    ["US-VA", "Virginia"],
    ["US-WA", "Washington"],
    ["US-WV", "West Virginia"],
    ["US-WI", "Wisconsin"],
    ["US-WY", "Wyoming"]
]

trends_countries = [
    ["AR", "Argentina"],
    ["AS", "American Samoa"],
    ["AT", "Austria"],
    ["AU", "Australia"],
    ["BB", "Barbados"],
    ["BR", "Brazil"],
    ["BS", "Bahamas"],
    ["BY", "Belarus"],
    ["CA", "Canada"],
    ["CH", "Switzerland"],
    ["CL", "Chile"],
    ["CO", "Colombia"],
    ["CR", "Costa Rica"],
    ["CU", "Cuba"],
    ["CZ", "Czechia"],
    ["DE", "Germany"],
    ["DK", "Denmark"],
    ["DO", "Dominican Republic"],
    ["EC", "Ecuador"],
    ["ES", "Spain"],
    ["FI", "Finland"],
    ["FR", "France"],
    ["GB", "United Kingdom"],
    ["GL", "Greenland"],
    ["GR", "Greece"],
    ["GT", "Guatemala"],
    ["HR", "Croatia"],
    ["HT", "Haiti"],
    ["HU", "Hungary"],
    ["IE", "Ireland"],
    ["IN", "India"],
    ["IS", "Iceland"],
    ["IT", "Italy"],
    ["JM", "Jamaica"],
    ["LI", "Liechtenstein"],
    ["LT", "Lithuania"],
    ["LU", "Luxembourg"],
    ["MH", "Marshall Islands"],
    ["MX", "Mexico"],
    ["NL", "Netherlands"],
    ["NO", "Norway"],
    ["NZ", "New Zealand"],
    ["PA", "Panama"],
    ["PE", "Peru"],
    ["PL", "Poland"],
    ["PR", "Puerto Rico"],
    ["PT", "Portugal"],
    ["PY", "Paraguay"],
    ["SE", "Sweden"],
    ["SV", "El Salvador"],
    ["TD", "Chad"],
    ["TR", "Turkey"],
    ["TZ", "Tanzania"],
    ["UA", "Ukraine"],
    ["UG", "Uganda"],
    ["US", "United States of America"],
    ["VE", "Venezuela"],
    ["ZA", "South Africa"],
    ["ZW", "Zimbabwe"]
]

foods = [
"Anchovies",
"Asparagus",
"Avocados",
"Arugula",
"Almonds",
"Apples ",
"Bacon",
"Bagels",
"Bananas",
"Barbecue",
"Barley",
"Basil",
"Beans",
"Beef",
"Beets",
"Blackberries",
"Blueberries",
"Bread",
"Broccoli",
"Burgers",
"Cabbage",
"Cake",
"Calzones",
"Cheese",
"Chicken",
"Chili",
"Coconut",
"Cod",
"Coffee",
"Cookies",
"Crepes",
"Curry",
"Dairy",
"Danishes",
"Dates",
"Dill",
"Dosa",
"Doubles",
"Doughnuts",
"Duck",
"Dumplings",
"Durian",
"Eclairs",
"Edamame",
"Eel",
"Eggnog",
"Eggplant",
"Eggrolls",
"Eggs",
"Empanadas",
"Enchiladas",
"Escargot",
"Espresso",
"Falafel",
"Fennel",
"Figs",
"Fish",
"French Fries",
"Frittatas",
"Frogs",
"Fruit",
"Gazpacho",
"Goose",
"Gooseberries",
"Graham Crackers",
"Granola",
"Grapes",
"Gravy",
"Guacamole",
"Gumbo",
"Gyoza",
"Gyros",
"Ham",
"Hamburger",
"Hash Browns",
"Herring",
"Hoisin Sauce",
"Honey",
"Honeydew",
"Horseradish",
"Hot Dogs",
"Hot Sauce",
"Huckleberries",
"Hummus",
"Ice Cream",
"Iceberg Lettuce",
"Italian Sausage",
"Jalapeno",
"Jam",
"Jambalaya",
"Jambon",
"Jelly",
"Jerk Chicken",
"Kale",
"Kasha",
"Kelp",
"Kimchi",
"Kombucha",
"Kumquats",
"Lasagna",
"Lemon",
"Lima Beans",
"Limes",
"Lingonberries",
"Lo Mein",
"Lollipop",
"Macaroon",
"Mango",
"Mangosteen",
"Maple Syrup",
"Margarine",
"Mayonnaise",
"Melon",
"Millet",
"Mochi",
"Mulberries",
"Mustard",
"Naan",
"Nachos",
"Natto",
"Navy Beans",
"Nectarines",
"Neufchatel Cheese",
"Noodles",
"Nori",
"Nougat",
"Nuts",
"Oatmeal",
"Octopus",
"Oil",
"Okra",
"Olives",
"Onion",
"Opossum",
"Oranges",
"Oregano",
"Oysters",
"Pad Thai",
"Pears",
"Peas",
"Pecans",
"Pepperoni",
"Peppers",
"Pie",
"Pork",
"Pumpkins",
"Quesadillas",
"Queso",
"Quetsch",
"Quiche",
"Quinces",
"Quinoa",
"Radishes",
"Raisins",
"Ramen",
"Raspberries",
"Ravioli",
"Relish",
"Rhubarb",
"Rice",
"Rigatoni",
"Romaine",
"Roquefort",
"Rye Bread",
"Salami",
"Sorbet",
"Soybeans",
"Spaghetti",
"Spinach",
"Squash",
"Sugar",
"Tacos",
"Tempeh",
"Tempura",
"Tiramisu",
"Tofu",
"Tomatoes",
"Tortellini",
"Truffles",
"Tuna",
"Turnips",
"Vanilla",
"Vegetables",
"Venison",
"Vinegar",
"Waffles",
"Walnuts",
"Wasabi",
"Watermelon",
"Wheat",
"Whelk",
"Whiting",
"Wine",
"Yams",
"Yeast",
"Yogurt",
"Ziti",
"Zucchini",
]
