version: "2.2"
services:
  trends-game:
    build:
      context: ./
      dockerfile: dockerfile
    image: michaelmason1998/trends_game/server

    container_name: Google-Trends-Game-Server
    ports:
      - 5000:5000
    networks:
      - app-network

networks:
  app-network:
    external: true
