version: "3.3"
services:
  trends-game:
    image: michaelmason1998/trends_game/server
    container_name: Google-Trends-Game-Server
    ports:
      - 5000:5000
    networks:
      - app-network
    depends_on:
      - trends-db

  trends-db:
    image: mysql
    restart: always
    container_name: Google-Trends-Game-MySQL
    environment:
      MYSQL_ROOT_PASSWORD: temp123
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: google_trends_schema
    volumes:
      - ./mysqlserver/mysql_data:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - app-network
    cap_add:
      - SYS_NICE

networks:
  app-network:
    external: true
